name: wifi
description: Flutter plugin providing WiFi.
author: Lewis <once10301@gmail.com>
homepage: https://github.com/once10301/wifi
version: 0.1.5

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.ly.wifi
    pluginClass: WifiPlugin

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.22.0 <2.0.0"
